# Generated by Django 5.2.6 on 2025-09-08 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICropAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering', models.TextField()),
                ('fertilization', models.TextField()),
                ('pest_risk', models.TextField()),
                ('harvest', models.TextField()),
                ('weather_alerts', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
